Repository elkarte/Elkarte, pull requests merged in 2018-03, with the labels that each got.

#3111 Added a prev/next arrow to the lightbox of attached images
  bootstrap.php
  sources/controllers/Recent.controller.php
  sources/subs/Auth.subs.php
  sources/subs/Search/Search.php
  themes/default/css/_besocial/index_besocial.css
  themes/default/css/_light/index_light.css
  themes/default/css/index.css
  themes/default/scripts/topic.js
Labels: enhancement, theme

#3117 Other fixes
  install/patch_1-1-2/modifications.xml
  install/patch_1-1-2/package-info.xml
  sources/Load.php
  sources/admin/ManageThemes.controller.php
  sources/database/Db-mysql.class.php
  sources/modules/Attachments/AttachmentsPostModule.class.php
  sources/subs/Attachments.subs.php
  sources/subs/Ila.integrate.php
  sources/subs/Mentions.subs.php
  sources/subs/PersonalMessage.subs.php
  themes/default/Post.template.php
  themes/default/Theme.php
  themes/default/css/_besocial/index_besocial.css
  themes/default/css/_light/index_light.css
  themes/default/css/index.css
  themes/default/languages/english/Post.english.php
  themes/default/scripts/elk_jquery_plugins.js
  themes/default/scripts/jquery.captcha.js
  themes/default/scripts/jquery.sceditor.elkarte.js
  themes/default/scripts/script_elk.js
Labels: block, bug

#3127 Bring 1.1.2 changes to development
  install/patch_1-1-2/modifications.xml
  install/patch_1-1-2/package-info.xml
  sources/Load.php
  sources/admin/ManageThemes.controller.php
  sources/controllers/Attachment.controller.php
  sources/controllers/Jslocale.controller.php
  sources/controllers/Recent.controller.php
  sources/controllers/Suggest.controller.php
  sources/controllers/Xml.controller.php
  sources/controllers/XmlPreview.controller.php
  sources/database/Db-mysql.class.php
  sources/modules/Attachments/AttachmentsPostModule.class.php
  sources/subs/Attachments.subs.php
  sources/subs/Auth.subs.php
  sources/subs/Ila.integrate.php
  sources/subs/Mentions.subs.php
  sources/subs/PersonalMessage.subs.php
  sources/subs/Search/Search.php
  sources/subs/Themes/ThemeLoader.php
  themes/default/Post.template.php
  themes/default/Theme.php
  themes/default/css/_besocial/index_besocial.css
  themes/default/css/_light/index_light.css
  themes/default/css/index.css
  themes/default/languages/english/ManageThemes.english.php
  themes/default/languages/english/Post.english.php
  themes/default/scripts/elk_jquery_plugins.js
  themes/default/scripts/jquery.captcha.js
  themes/default/scripts/jquery.sceditor.elkarte.js
  themes/default/scripts/script_elk.js
  themes/default/scripts/topic.js
Labels: block, bug, enhancement

#3123 Some early bug fixes
  install/upgrade_1-1.php
  sources/Subs.php
  sources/controllers/ProfileOptions.controller.php
Labels: bug

#3130 Search security fix
  bootstrap.php
  install/installcore.php
  install/patch_1-1-3/modifications.xml
  install/patch_1-1-3/package-info.xml
  sources/Subs.php
  sources/controllers/ProfileOptions.controller.php
  sources/controllers/Search.controller.php
  sources/subs/Search/Search.php
Labels: Security, block, bug, regression

#3137 Removed backticks and updated to latest version of badbehaviour
  sources/ext/bad-behavior/bad-behavior/core.inc.php
  sources/ext/bad-behavior/bad-behavior/screener.inc.php
  sources/ext/bad-behavior/badbehavior-plugin.php
Labels: bug
