Repository elkarte/Elkarte, pull requests merged in 2018-05, with the labels that each got.

#3167 Some fix
  sources/Subs.php
  sources/controllers/MessageIndex.controller.php
  sources/controllers/Register.controller.php
  sources/subs/MentionType/MailfailMention.php
  sources/subs/MentionType/MentionMessageAbstract.php
  sources/subs/MentionType/MentionmemMention.php
  sources/subs/MentionType/QuotedmemMention.php
  themes/default/index.template.php
Labels: bug

#3188 1.1.4 Patch items
  install/CommonCode.php
  install/upgrade.php
  sources/BrowserDetector.class.php
  sources/admin/ManageAttachments.controller.php
  sources/admin/ManageLanguages.controller.php
  sources/admin/ManageSmileys.controller.php
  sources/admin/ManageThemes.controller.php
  sources/controllers/Notify.controller.php
  sources/ext/simple_html_dom.php
  sources/subs/Cache.class.php
  sources/subs/CacheMethod/Filebased.php
  sources/subs/Html2Md.class.php
  sources/subs/Likes.subs.php
  sources/subs/Mail.subs.php
  sources/subs/MessageIcons.subs.php
  sources/subs/MessageTopicIcons.class.php
  sources/subs/Package.subs.php
  sources/subs/SettingsFormAdapter/File.php
  sources/subs/TopicUtil.class.php
  themes/default/Admin.template.php
  themes/default/BoardIndex.template.php
  themes/default/Display.template.php
  themes/default/MessageIndex.template.php
  themes/default/ProfileInfo.template.php
  themes/default/css/_besocial/icons_svg_besocial.css
  themes/default/css/_besocial/index_besocial.css
  themes/default/css/_light/index_light.css
  themes/default/css/index.css
  themes/default/scripts/like_posts.js
Labels: block, bug

#3187 Minor updates for packlist
  composer.json
Labels: Wording

#3191 User agreement and privacy policy
  install/Install_Controller.php
  install/install_1-1.php
  install/upgrade_1-1.php
  privacypolicy.txt
  sources/Load.php
  sources/Subs.php
  sources/admin/Admin.controller.php
  sources/admin/ManageRegistration.controller.php
  sources/controllers/Jslocale.controller.php
  sources/controllers/Register.controller.php
  sources/subs/Agreement.class.php
  sources/subs/Members.subs.php
  sources/subs/PrivacyPolicy.class.php
  themes/default/Register.template.php
  themes/default/Theme.php
  themes/default/css/index.css
  themes/default/index.template.php
  themes/default/languages/english/Admin.english.php
  themes/default/languages/english/Errors.english.php
  themes/default/languages/english/Login.english.php
  themes/default/languages/english/Profile.english.php
  themes/default/languages/english/index.english.php
  themes/default/scripts/admin.js
  themes/default/scripts/register.js
Labels: GDPR, enhancement
