Repository elkarte/Elkarte, pull requests merged in 2018-06, with the labels that each got.

#3200 Last minute fixes
  SSI.php
  email_imap_cron.php
  emailpost.php
  emailtopic.php
  sources/controllers/Register.controller.php
  sources/subs/MentionType/MentionMessageAbstract.php
  sources/subs/MentionType/MentionTypeInterface.php
  sources/subs/MentionType/QuotedmemMention.php
  sources/subs/MentionType/RlikemsgMention.php
  sources/subs/Mentioning.php
  sources/subs/Notifications.class.php
  sources/subs/Profile.subs.php
  subscriptions.php
Labels: block, bug

#3201 Last *cough* of the 1.1.4 things
  sources/subs/Ila.integrate.php
  themes/default/css/index.css
  themes/default/css/rtl.css
Labels: bug, enhancement

#3202 A few more 1.1.4 fixes
  SSI.php
  docs/readme_update.html
  docs/readme_upgrade.html
  sources/subs/Ila.integrate.php
  sources/subs/Unread.class.php
  themes/default/Register.template.php
  themes/default/css/_light/rtl_light.css
  themes/default/css/index.css
  themes/default/languages/english/Help.english.php
  themes/default/scripts/script_elk.js
Labels: block, bug

#3204 Update of all the versions of files that was not updated before
  bootstrap.php
  email_imap_cron.php
  emailpost.php
  emailtopic.php
  install/installcore.php
  sources/BrowserDetector.class.php
  sources/Load.php
  sources/SiteCombiner.class.php
  sources/admin/Admin.controller.php
  sources/admin/ManageFeatures.controller.php
  sources/admin/ManageRegistration.controller.php
  sources/controllers/Jslocale.controller.php
  sources/controllers/MessageIndex.controller.php
  sources/controllers/Recent.controller.php
  sources/controllers/Register.controller.php
  sources/subs/Agreement.class.php
  sources/subs/Errors/Errors.php
  sources/subs/Exception/ElkException.class.php
  sources/subs/Likes.subs.php
  sources/subs/Memberlist.subs.php
  sources/subs/Members.subs.php
  sources/subs/MentionType/MailfailMention.php
  sources/subs/MentionType/MentionMessageAbstract.php
  sources/subs/MentionType/MentionTypeInterface.php
  sources/subs/MentionType/MentionmemMention.php
  sources/subs/MentionType/QuotedmemMention.php
  sources/subs/MentionType/RlikemsgMention.php
  sources/subs/Mentioning.php
  sources/subs/Notifications.class.php
  sources/subs/Package.subs.php
  sources/subs/PersonalMessage.subs.php
  sources/subs/Priority.class.php
  sources/subs/Profile.subs.php
  ssi_examples.php
  subscriptions.php
  themes/default/Admin.template.php
  themes/default/GenericMessages.template.php
  themes/default/ManageFeatures.template.php
  themes/default/Register.template.php
  themes/default/Theme.php
  themes/default/index.template.php
Labels: block

#3205 Some more versions updated
  release_tools/generate_detailed-version.php
  sources/subs/PrivacyPolicy.class.php
Labels: block

#3212 Missing file update and fix to detailed versions
  install/patch_1-1-4/modifications.xml
  release_tools/generate_detailed-version.php
  sources/subs/Attachments.subs.php
Labels: block, bug
