Repository elkarte/Elkarte, pull requests merged in 2018-04, with the labels that each got.

#3154 Dealing with early errors
  sources/Load.php
  sources/subs/Errors/Errors.php
  sources/subs/Exception/ElkException.class.php
  themes/default/css/index.css
Labels: bug, db

#3122 Refactor/errors
  sources/admin/ManageErrors.controller.php
  sources/database/Db-mysql.class.php
  sources/subs/Errors/AttachmentErrorContext.php
  sources/subs/Errors/ErrorContext.php
  sources/subs/Errors/ErrorHandler.php
  sources/subs/Errors/Errors.php
  sources/subs/Errors/Log.php
  sources/subs/Exception/ControllerRedirectException.class.php
  sources/subs/Exception/ElkException.class.php
  sources/subs/Themes/Templates.php
  themes/default/Errors.template.php
  themes/default/css/_besocial/index_besocial.css
  themes/default/css/_light/admin_light.css
  themes/default/css/admin.css
  themes/default/css/index.css
Labels: enhancement

#3161 My114
  sources/admin/PackageServers.controller.php
  sources/admin/Packages.controller.php
  sources/controllers/ProfileOptions.controller.php
  themes/default/css/admin.css
  themes/default/css/index.css
  themes/default/scripts/jquery.sceditor.elkarte.js
Labels: bug, theme

#3157 And here it is: allow using the keys as substitution parameter for radio and select custom fields
  install/install_1-1.php
  install/upgrade_1-1.php
  sources/Load.php
  sources/admin/ManageFeatures.controller.php
  sources/controllers/Recent.controller.php
  sources/subs/Ila.integrate.php
  sources/subs/Memberlist.subs.php
  sources/subs/Profile.subs.php
  themes/default/ManageFeatures.template.php
  themes/default/css/admin.css
  themes/default/css/icons_svg.css
  themes/default/languages/english/Admin.english.php
  themes/default/languages/english/Help.english.php
  themes/default/scripts/admin.js
Labels: enhancement

#3166 Update Admin.subs.php
  sources/subs/Admin.subs.php
Labels: bug
