Repository elkarte/Elkarte, pull requests merged in 2019-05, with the labels that each got.

#3312 Address #3238
  sources/subs/Html2Md.class.php
  sources/subs/Members.subs.php
  tests/sources/subs/HTML2Md.class.Basic.php
Labels: bug

#3315 Updates for 1.1.6 mainly for 7.3
  .travis.yml
  install/install.php
  install/installcore.php
  install/upgrade.php
  sources/Templates.class.php
  sources/admin/Admin.controller.php
  sources/admin/Maintenance.controller.php
  sources/admin/ManageAttachments.controller.php
  sources/admin/ManageBans.controller.php
  sources/admin/ManageSecurity.controller.php
  sources/admin/PackageActions.class.php
  sources/admin/Packages.controller.php
  sources/controllers/Attachment.controller.php
  sources/controllers/Groups.controller.php
  sources/controllers/Members.controller.php
  sources/controllers/MergeTopics.controller.php
  sources/controllers/ModerationCenter.controller.php
  sources/controllers/PostModeration.controller.php
  sources/controllers/ProfileOptions.controller.php
  sources/controllers/Register.controller.php
  sources/controllers/SplitTopics.controller.php
  sources/controllers/XmlPreview.controller.php
  sources/database/Db-abstract.class.php
  sources/ext/GoogleAuthenticator.php
  sources/ext/bad-behavior/bad-behavior/core.inc.php
  sources/ext/bad-behavior/bad-behavior/post.inc.php
  sources/ext/markdown/Michelf/Markdown.php
  sources/ext/markdown/Michelf/MarkdownExtra.php
  sources/ext/markdown/Michelf/MarkdownInterface.php
  sources/ext/markdown/markdown.php
  sources/ext/simple_html_dom.php
  sources/subs/Attachments.subs.php
  sources/subs/XmlArray.class.php
  tests/sources/subs/HTML2BBC.class.Basic.php
  tests/sources/subs/MD2HTML.class.Basic.php
  themes/default/languages/english/Help.english.php
  themes/default/languages/english/ManageSettings.english.php
Labels: bug, enhancement

#3316 A few files that were not updated
  sources/Load.php
  sources/Templates.class.php
  sources/admin/Maintenance.controller.php
  sources/admin/ManageSecurity.controller.php
  sources/database/Db-abstract.class.php
  sources/subs/Attachments.subs.php
  sources/subs/DataValidator.class.php
  sources/subs/HttpReq.class.php
  sources/subs/Ila.integrate.php
  sources/subs/XmlArray.class.php
  themes/default/ManageSmileys.template.php
Labels: block
