Repository elkarte/Elkarte, pull requests merged in 2019-08, with the labels that each got.

#3289 Some necessary fixes for code I broke "recently"
  sources/ElkArte/BoardsList.php
  sources/ElkArte/Subscriptions/PaymentGateway/Authorize/Display.php
  sources/ElkArte/Subscriptions/PaymentGateway/Authorize/Payment.php
  sources/ElkArte/Subscriptions/PaymentGateway/DisplayInterface.php
  sources/ElkArte/Subscriptions/PaymentGateway/PayPal/Display.php
  sources/ElkArte/Subscriptions/PaymentGateway/PayPal/Payment.php
  sources/ElkArte/Subscriptions/PaymentGateway/PaymentInterface.php
  sources/ElkArte/Subscriptions/PaymentGateway/TwoCheckOut/Display.php
  sources/ElkArte/Subscriptions/PaymentGateway/TwoCheckOut/Payment.php
  sources/subs/Memberlist.subs.php
  sources/subs/PaidSubscriptions.subs.php
  tests/sources/subs/Http/Curl_Fetch_Webdata.class.Test.php
Labels: block, bug

#3334 Fix a few annoyances in the package manager
  sources/ElkArte/AdminController/Maintenance.php
  sources/ElkArte/AdminController/PackageActions.php
  sources/ElkArte/AdminController/PackageServers.php
  sources/ElkArte/AdminController/Packages.php
  sources/ElkArte/UnTgz.php
  sources/ElkArte/UnZip.php
  sources/Subs.php
  sources/subs/Package.subs.php
  themes/default/PackageServers.template.php
  themes/default/Packages.template.php
  themes/default/scripts/admin.js
Labels: bug, enhancement

#3336 Ci tweaks
  .travis.yml
  tests/ExitHandler.php
  tests/append.php
  tests/prepend.php
  tests/sources/controllers/RecentPostsTest.php
  tests/travis-ci/BootstrapRunTestExt.php
  tests/travis-ci/DatabaseTestExt.php
  tests/travis-ci/Elk_Testing_psql.php
  tests/travis-ci/bootstrap.php
  tests/travis-ci/phpunit-basic-travis.xml
  tests/travis-ci/phpunit-mariadb-travis.xml
  tests/travis-ci/phpunit-mysql-travis.xml
  tests/travis-ci/phpunit-postgres-travis.xml
  tests/travis-ci/phpunit-with-webtest-mariadb-travis.xml
  tests/travis-ci/phpunit-with-webtest-mysql-travis.xml
  tests/travis-ci/phpunit-with-webtest-postgres-travis.xml
  tests/travis-ci/setup-failure.sh
  tests/travis-ci/setup-results.sh
  tests/travis-ci/setup-script.sh
  tests/travis-ci/setup-selenium.sh
  tests/travis-ci/setup.php
  tests/travis-ci/travis-ci-apache
  tests/travis-ci/travis_php.ini
  tests/travis-ci/travis_webtest_php.ini
Labels: enhancement
