Repository elkarte/Elkarte, pull requests merged in 2019-04, with the labels that each got.

#3300 Some Fixes for 1.1.6
  sources/admin/Packages.controller.php
  sources/controllers/Attachment.controller.php
  sources/controllers/Post.controller.php
  sources/controllers/ProfileHistory.controller.php
  sources/controllers/Register.controller.php
  sources/modules/Calendar/CalendarPostModule.class.php
  sources/subs/CalendarEvent.class.php
  sources/subs/Graphics.subs.php
  sources/subs/Search/API/Sphinxql.php
  sources/subs/VerificationControls.class.php
  tests/travis-ci/setup-server.sh
  themes/default/Post.template.php
  themes/default/VerificationControls.template.php
  themes/default/css/index.css
  themes/default/languages/english/LikePosts.english.php
  themes/default/languages/english/ManageSettings.english.php
  themes/default/scripts/jquery.captcha.js
  themes/default/scripts/like_posts.js
Labels: bug, enhancement

#3301 A couple of more 1.1.6 fixes
  install/Install_Controller.php
  themes/default/scripts/mentioning.plugin.js
Labels: bug

#3304 The two "security" issues open
  SSI.php
  install/install.php
  sources/subs/Recent.class.php
  sources/subs/Search/Search.php
Labels: Security, block, bug

#3305 This will stop the error, the directory creation is another item
  sources/admin/ManageAttachments.controller.php
Labels: bug

#3303 Update Session.php to secure PHPSESSIONID
  sources/Session.php
Labels: enhancement

#3307 Ban error for 1.1.6 and headers
  sources/Session.php
  sources/admin/ManageBans.controller.php
Labels: bug

#3308 Update missing headers and versions in index and install
  SSI.php
  bootstrap.php
  install/installcore.php
  sources/controllers/MessageIndex.controller.php
  sources/controllers/ProfileOptions.controller.php
  sources/database/Db-mysql.class.php
  sources/subs/BBC/Codes.php
  sources/subs/PaidSubscriptions.subs.php
  sources/subs/Recent.class.php
  sources/subs/Search/Search.php
  themes/default/ManageSearch.template.php
Labels: block
