Repository elkarte/Elkarte, pull requests merged in 2020-12, with the labels that each got.

#3412 Fixed hard-coded insert string to insert ILA attachments in posts
  themes/default/Post.template.php
  themes/default/languages/english/Post.english.php
Labels: block, bug

#3416 PHP 7.4 updates and "other"
  .travis.yml
  Settings.sample.php
  sources/BrowserDetector.class.php
  sources/Load.php
  sources/admin/ManageAttachments.controller.php
  sources/admin/ManageMaillist.controller.php
  sources/controllers/Emailpost.controller.php
  sources/controllers/ProfileInfo.controller.php
  sources/controllers/Spellcheck.controller.php
  sources/controllers/Xml.controller.php
  sources/subs/Attachments.subs.php
  sources/subs/BBC/BBCParser.php
  sources/subs/BBC/Codes.php
  sources/subs/Drafts.subs.php
  sources/subs/EmailFormat.class.php
  sources/subs/EmailParse.class.php
  sources/subs/Emailpost.subs.php
  sources/subs/Graphics.subs.php
  sources/subs/Html2BBC.class.php
  sources/subs/Html2Md.class.php
  sources/subs/Mail.subs.php
  sources/subs/Notification.subs.php
  sources/subs/RepairBoards.subs.php
  sources/subs/Unread.class.php
  sources/subs/VerificationControls.class.php
  tests/sources/subs/HTML2Md.class.Basic.php
  tests/travis-ci/setup-server.sh
  themes/default/Maillist.template.php
  themes/default/css/index.css
Labels: block, bug

#3418 Address more of #3225
  bootstrap.php
  install/TemplateUpgrade.php
  install/upgrade.php
  themes/default/css/install.css
  themes/default/languages/english/Install.english.php
Labels: enhancement

#3420 Add samesite parameter to set cookie
  sources/subs/Auth.subs.php
Labels: enhancement

#3421 Some php 8 prepping
  bootstrap.php
  sources/Debug.class.php
  sources/Hooks.class.php
  sources/SiteDispatcher.class.php
  sources/admin/CoreFeatures.controller.php
  sources/admin/ManageErrors.controller.php
  sources/admin/ManageFeatures.controller.php
  sources/admin/ManageLanguages.controller.php
  sources/admin/Packages.controller.php
  sources/controllers/PersonalMessage.controller.php
  sources/modules/Drafts/DraftsPersonalMessageModule.class.php
  sources/subs/CacheMethod/Memcached.php
  sources/subs/Errors/Errors.php
  sources/subs/EventManager.class.php
  sources/subs/Exception/ElkException.class.php
  sources/subs/Package.subs.php
  sources/subs/Poll.subs.php
  sources/subs/QueryAnalysis.class.php
  sources/subs/SessionHandler/DatabaseHandler.php
  sources/subs/SettingsFormAdapter/File.php
  themes/default/scripts/drafts.plugin.js
  themes/default/scripts/push.min.js
Labels: bug

#3425 Fix multiple issues / annoyances in manage attachments
  sources/admin/ManageAttachments.controller.php
Labels: bug

#3426 A few more items
  sources/BrowserDetector.class.php
  sources/Debug.class.php
  sources/Subs.php
  sources/admin/ManageCalendarModule.controller.php
  sources/admin/ManageErrors.controller.php
  sources/admin/ManageSmileys.controller.php
  sources/controllers/Xml.controller.php
  sources/subs/Compat.subs.php
  sources/subs/Emailpost.subs.php
  sources/subs/Notification.subs.php
  sources/subs/QueryAnalysis.class.php
  sources/subs/SessionHandler/DatabaseHandler.php
  sources/subs/Smileys.subs.php
  themes/default/Maillist.template.php
  themes/default/Notify.template.php
  themes/default/Post.template.php
  themes/default/css/index.css
  themes/default/scripts/script_elk.js
Labels: bug
