Repository elkarte/Elkarte, pull requests merged in 2020-01, with the labels that each got.

#3377 Some more 1.1.7 updates and fixes
  README.md
  docs/readme_install.html
  docs/readme_update.html
  docs/readme_upgrade.html
  install/install.php
  install/installcore.php
  install/upgrade.php
  sources/CurlFetchWebdata.class.php
  sources/Hooks.class.php
  sources/Security.php
  sources/Server.class.php
  sources/Subs.php
  sources/controllers/News.controller.php
  sources/controllers/PersonalMessage.controller.php
  sources/controllers/Register.controller.php
  sources/controllers/Unread.controller.php
  sources/subs/Admin.subs.php
  sources/subs/BBC/BBCParser.php
  sources/subs/Compat.subs.php
  sources/subs/EventManager.class.php
  sources/subs/Memberlist.subs.php
  sources/subs/MessagesDelete.class.php
  sources/subs/Package.subs.php
  sources/subs/RepairBoards.subs.php
  sources/subs/ScheduledTask/UserAccessMentions.php
  sources/subs/Themes.subs.php
  sources/subs/Topic.subs.php
  sources/subs/Unread.class.php
  sources/subs/Util.class.php
  ssi_examples.php
  ssi_examples.shtml
  tests/sources/controllers/MessageIndexTest.php
  tests/sources/controllers/ProfileInfoTest.php
  tests/sources/controllers/RecentPostsTest.php
  themes/default/GenericMessages.template.php
  themes/default/ProfileInfo.template.php
  themes/default/Xml.template.php
  themes/default/css/_light/index_light.css
  themes/default/css/index.css
  themes/default/languages/english/Admin.english.php
  themes/default/languages/english/Help.english.php
  themes/default/languages/english/Install.english.php
  themes/default/languages/english/ManageBoards.english.php
  themes/default/languages/english/ManageThemes.english.php
  themes/default/languages/english/index.english.php
  themes/default/scripts/elk_jquery_plugins.js
Labels: bug

#3391 Menus Update
  sources/ElkArte/AdminController/Admin.php
  sources/ElkArte/Controller/ModerationCenter.php
  sources/ElkArte/Controller/PersonalMessage.php
  sources/ElkArte/Controller/Profile.php
  sources/ElkArte/Menu/Menu.php
  sources/ElkArte/Menu/MenuArea.php
  sources/ElkArte/Menu/MenuItem.php
  sources/ElkArte/Menu/MenuOptions.php
  sources/ElkArte/Menu/MenuSection.php
  sources/ElkArte/Menu/MenuSubsection.php
  sources/subs/Menu.subs.php
  tests/sources/admin/AdminSearchTest.php
  tests/sources/subs/Menu.class.Test.php
  tests/sources/subs/Menu.subs.Test.php
  themes/default/GenericMenu.template.php
  themes/default/css/_besocial/index_besocial.css
  themes/default/css/_besocial/rtl_besocial.css
  themes/default/css/_light/index_light.css
  themes/default/css/_light/rtl_light.css
  themes/default/css/index.css
Labels: enhancement

#3389 Unsubscribe improvements
  sources/SiteDispatcher.class.php
  sources/admin/ManageFeatures.controller.php
  sources/controllers/Likes.controller.php
  sources/controllers/Members.controller.php
  sources/controllers/Notify.controller.php
  sources/subs/ManageFeatures.subs.php
  sources/subs/Members.subs.php
  sources/subs/MentionType/LikemsgMention.php
  sources/subs/MentionType/MailfailMention.php
  sources/subs/MentionType/MentionMessageAbstract.php
  sources/subs/MentionType/MentionTypeInterface.php
  sources/subs/MentionType/MentionmemMention.php
  sources/subs/MentionType/QuotedmemMention.php
  sources/subs/MentionType/RlikemsgMention.php
  sources/subs/Notification.subs.php
  sources/subs/NotificationsTask.class.php
  sources/subs/ProfileOptions.subs.php
  themes/default/Notify.template.php
  themes/default/languages/english/EmailTemplates.english.php
  themes/default/languages/english/MaillistTemplates.english.php
  themes/default/languages/english/index.english.php
Labels: bug, enhancement

#3367 [WIP] First round of miving the management of temporary attachments to its own class
  sources/ElkArte/AdminController/ManageAttachments.php
  sources/ElkArte/AttachmentsDirectory.php
  sources/ElkArte/Controller/Attachment.php
  sources/ElkArte/Controller/Display.php
  sources/ElkArte/Modules/Attachments/Post.php
  sources/ElkArte/TemporaryAttachment.php
  sources/ElkArte/TemporaryAttachmentsList.php
  sources/ElkArte/ValuesContainer.php
  sources/subs/Attachments.subs.php
  sources/subs/Emailpost.subs.php
  sources/subs/Profile.subs.php
  themes/default/languages/english/Admin.english.php
  themes/default/languages/english/Help.english.php
Labels: enhancement, question
