Repository elkarte/Elkarte, pull requests merged in 2021-01, with the labels that each got.

#3428 Query to fetch
  SSI.php
  install/upgrade.php
  sources/ElkArte/Database/AbstractQuery.php
  sources/ElkArte/Database/Postgresql/Query.php
  sources/ElkArte/Database/QueryInterface.php
  sources/ElkArte/Errors/Log.php
  sources/ElkArte/OpenID.php
  sources/ElkArte/Unread.php
  sources/subs/Attachments.subs.php
  sources/subs/BadBehavior.subs.php
  sources/subs/Bans.subs.php
  sources/subs/Logging.subs.php
  sources/subs/Maintenance.subs.php
  sources/subs/Memberlist.subs.php
  sources/subs/MessageIndex.subs.php
  sources/subs/PaidSubscriptions.subs.php
  sources/subs/PersonalMessage.subs.php
  sources/subs/Post.subs.php
  sources/subs/Recent.subs.php
  sources/subs/ScheduledTasks.subs.php
  sources/subs/SearchEngines.subs.php
  sources/subs/Stats.subs.php
  sources/subs/Themes.subs.php
  sources/subs/Who.subs.php
Labels: db, enhancement

#3436 Post Updates
  sources/ElkArte/Controller/Post.php
  sources/ElkArte/DataValidator.php
  sources/ElkArte/Database/AbstractResult.php
  sources/ElkArte/Database/Mysqli/Table.php
  sources/ElkArte/Database/Postgresql/Table.php
  sources/ElkArte/Database/QueryInterface.php
  sources/ElkArte/Database/SearchInterface.php
  sources/ElkArte/Errors/Errors.php
  sources/ElkArte/HttpReq.php
  sources/ElkArte/IlaIntegrate.php
  sources/ElkArte/Mentions/Mentioning.php
  sources/ElkArte/TokenHash.php
  sources/ElkArte/TopicsMerge.php
  sources/Security.php
  sources/Subs.php
  sources/database/Database.subs.php
  sources/ext/JSqueeze.php
  sources/subs/Admin.subs.php
  sources/subs/Notification.subs.php
  sources/subs/PaidSubscriptions.subs.php
  sources/subs/Poll.subs.php
  sources/subs/Post.subs.php
  sources/subs/Topic.subs.php
  themes/default/ManageMembergroups.template.php
Labels: bug, enhancement

#3437 Attach updates
  sources/ElkArte/AttachmentsDirectory.php
  sources/ElkArte/Controller/Attachment.php
  sources/ElkArte/Graphics/Image.php
  sources/ElkArte/Graphics/Manipulators/AbstractManipulator.php
  sources/ElkArte/Graphics/Manipulators/Gd2.php
  sources/ElkArte/Graphics/Manipulators/Imagick.php
  sources/ElkArte/Graphics/TextImage.php
  sources/ElkArte/Modules/Attachments/Post.php
  sources/ElkArte/TemporaryAttachment.php
  sources/ElkArte/TemporaryAttachmentsList.php
  sources/subs/Attachments.subs.php
  sources/subs/ManageAttachments.subs.php
  sources/subs/Messages.subs.php
Labels: bug, enhancement

#3440 Update querys from MySQL unique LIMIT offset, start to more universal LIMIT start OFFSET offset
  sources/ElkArte/Database/Mysqli/Dump.php
  sources/ElkArte/Database/Postgresql/Dump.php
  sources/ElkArte/Database/Postgresql/Query.php
  sources/ElkArte/Errors/Log.php
  sources/ElkArte/Recent.php
  sources/ElkArte/ScheduledTasks/Tasks/UserAccessMentions.php
  sources/ElkArte/Search/API/Sphinxql.php
  sources/ElkArte/Search/API/Standard.php
  sources/ElkArte/Unread.php
  sources/subs/BadBehavior.subs.php
  sources/subs/Bans.subs.php
  sources/subs/Calendar.subs.php
  sources/subs/Likes.subs.php
  sources/subs/Maillist.subs.php
  sources/subs/ManageAttachments.subs.php
  sources/subs/Membergroups.subs.php
  sources/subs/Members.subs.php
  sources/subs/Mentions.subs.php
  sources/subs/MessageIndex.subs.php
  sources/subs/Messages.subs.php
  sources/subs/Moderation.subs.php
  sources/subs/Modlog.subs.php
  sources/subs/PaidSubscriptions.subs.php
  sources/subs/PersonalMessage.subs.php
  sources/subs/Profile.subs.php
  sources/subs/ProfileHistory.subs.php
  sources/subs/ScheduledTasks.subs.php
  sources/subs/SearchEngines.subs.php
  sources/subs/Smileys.subs.php
  sources/subs/Topic.subs.php
Labels: db, enhancement

#3441 Search Updates
  sources/ElkArte/AdminController/ManageSearch.php
  sources/ElkArte/Controller/Search.php
  sources/ElkArte/DataValidator.php
  sources/ElkArte/Database/AbstractSearch.php
  sources/ElkArte/Search/API/Custom.php
  sources/ElkArte/Search/API/Fulltext.php
  sources/ElkArte/Search/API/Standard.php
  sources/ElkArte/Search/SearchParams.php
  sources/subs/ManageSearch.subs.php
Labels: bug, enhancement

#3439 Draft updates
  sources/ElkArte/Controller/Display.php
  sources/ElkArte/Controller/Post.php
  sources/ElkArte/Modules/Drafts/Display.php
  sources/ElkArte/Modules/Drafts/PersonalMessage.php
  sources/ElkArte/Modules/Drafts/Post.php
  themes/default/Display.template.php
  themes/default/Post.template.php
  themes/default/css/index.css
  themes/default/css/rtl.css
  themes/default/languages/english/Post.english.php
Labels: bug, enhancement

#3438 Update SCEditor to V2.3.1
  .jshintignore
  install/TemplateUpgrade.php
  sources/ElkArte/AdminController/Admin.php
  sources/ElkArte/AdminController/ManageEditor.php
  sources/ElkArte/AdminController/ManagePosts.php
  sources/ElkArte/BBC/BBCParser.php
  sources/ElkArte/Controller/Jslocale.php
  sources/subs/Editor.subs.php
  tests/sources/controllers/PersonalMessageTest.php
  tests/sources/subs/BBC.subs.Test.php
  themes/default/GenericControls.template.php
  themes/default/Theme.php
  themes/default/css/_besocial/jquery.sceditor.elk_wiz_besocial.css
  themes/default/css/_light/jquery.sceditor.elk_wiz_light.css
  themes/default/css/jquery.sceditor.css
  themes/default/languages/english/Admin.english.php
  themes/default/scripts/bbcode.js
  themes/default/scripts/drafts.plugin.js
  themes/default/scripts/jquery-3.1.1.min.js
  themes/default/scripts/jquery-3.5.1.min.js
  themes/default/scripts/jquery.sceditor.bbcode.min.js
  themes/default/scripts/jquery.sceditor.elkarte.js
  themes/default/scripts/mentioning.plugin.js
  themes/default/scripts/post.js
  themes/default/scripts/script_elk.js
  themes/default/scripts/spellcheck.js
  themes/default/scripts/splittag.plugin.js
  themes/default/scripts/undo.plugin.min.js
Labels: bug, enhancement

#3442 Search updates II
  sources/ElkArte/AdminController/ManageSearch.php
  sources/ElkArte/Controller/PersonalMessage.php
  sources/ElkArte/Controller/Search.php
  sources/ElkArte/MessagesCallback/SearchRenderer.php
  sources/ElkArte/Search/API/AbstractAPI.php
  sources/ElkArte/Search/API/Custom.php
  sources/ElkArte/Search/API/Fulltext.php
  sources/ElkArte/Search/API/Sphinx.php
  sources/ElkArte/Search/API/Sphinxql.php
  sources/ElkArte/Search/API/Standard.php
  sources/ElkArte/Search/Search.php
  sources/ElkArte/Search/SearchApiWrapper.php
  sources/ElkArte/Search/SearchArray.php
  sources/ElkArte/Search/SearchParams.php
  sources/ElkArte/TopicUtil.php
  sources/subs/ManageSearch.subs.php
  sources/subs/MessageIndex.subs.php
  sources/subs/Post.subs.php
  sources/subs/RepairBoards.subs.php
  tests/sources/subs/Search.class.Test.php
  themes/default/ManageSearch.template.php
  themes/default/Search.template.php
  themes/default/index.template.php
  themes/default/languages/english/Errors.english.php
  themes/default/languages/english/Search.english.php
Labels: bug, enhancement

#3432 Fix broken notification saves in profile area
  install/install_1-1.php
  install/upgrade_1-1.php
  sources/ElkArte/Controller/Notify.php
  sources/ElkArte/Notifications.php
  sources/ElkArte/Notifiers/Methods/EmailDaily.php
  sources/ElkArte/Notifiers/Methods/EmailWeekly.php
  sources/ElkArte/UrlGenerator/Standard/Standard.php
  sources/subs/Emailpost.subs.php
  sources/subs/Notification.subs.php
  sources/subs/Profile.subs.php
  sources/subs/Topic.subs.php
  tests/sources/subs/Mention.subs.Test.php
  themes/default/ProfileOptions.template.php
Labels: bug
