Repository elkarte/Elkarte, pull requests merged in 2021-02, with the labels that each got.

#3444 GHA to replace Travis
  .github/ElkTestingMysql.php
  .github/ElkTestingPsql.php
  .github/SetupDbUtil.php
  .github/SetupMysql.php
  .github/SetupPgsql.php
  .github/bootstrap.php
  .github/nginx.conf
  .github/phpunit-basic.xml
  .github/phpunit-mariadb.xml
  .github/phpunit-mysql.xml
  .github/phpunit-postgres.xml
  .github/phpunit-static.xml
  .github/phpunit-with-webtest-mysql.xml
  .github/setup-database.sh
  .github/setup-elkarte.sh
  .github/setup-failure.sh
  .github/setup-nginx.sh
  .github/setup-results.sh
  .github/setup-selenium.sh
  .github/webtest_php.ini
  .github/workflows/tests.yaml
  .jshintignore
  .stylelintignore
  .travis.yml
  tests/BootstrapRunTestExt.php
  tests/DatabaseTestExt.php
  tests/sources/FilesTest.Static.php
  tests/sources/subs/Calendar_Event.class.Test.php
  tests/sources/subs/Http/Curl_Fetch_Webdata.class.Test.php
  tests/travis-ci/setup-elkarte.sh
  tests/travis-ci/setup-results.sh
  tests/travis-ci/setup-script.sh
  tests/travis-ci/setup-server.sh
  tests/travis-ci/setup_pgsql.php
  tests/travis-ci/travis-archive.zip
  tests/travis-ci/travis-ci-apache
  tests/travis-ci/travis-fpm.sh
  tests/travis-ci/travis_php.ini
Labels: enhancement

#3449 Chromedriver
  .github/setup-failure.sh
  .github/setup-selenium.sh
  .github/workflows/tests.yaml
  sources/ElkArte/AdminController/Admin.php
  sources/ElkArte/AdminController/ManageMembers.php
  sources/ElkArte/AdminController/ManageRegistration.php
  tests/install/ElkArteInstallWeb.php
  tests/sources/controllers/AttachmentTest.php
  tests/sources/controllers/AuthWeb.php
  tests/sources/controllers/ElkArteWebSupport.php
  tests/sources/controllers/EmailUserTest.php
  tests/sources/controllers/PostTest.php
  tests/sources/controllers/RegisterWeb.php
  tests/sources/controllers/acpAddGroupWeb.php
  tests/sources/controllers/acpManageMembersWeb.php
Labels: enhancement

#3454 Additoanl Test tweaks
  sources/ElkArte/AttachmentsDirectory.php
  sources/subs/Stats.subs.php
  tests/install/ElkArteInstallWeb.php
  tests/sources/controllers/AuthWeb.php
  tests/sources/controllers/ElkArteWebSupport.php
  tests/sources/controllers/PostTestWeb.php
  tests/sources/controllers/ProfileForumWeb.php
  tests/sources/controllers/ProfileInfoWeb.php
  tests/sources/controllers/RegisterWeb.php
  tests/sources/controllers/acpAddGroupWeb.php
  tests/sources/controllers/acpManageMembersWeb.php
  tests/sources/subs/Boards.subs.Test.php
Labels: enhancement

#3459 Search updates
  install/Db-check-MySQLi.php
  install/Db-check-PostgreSQL.php
  install/installcore.php
  sources/ElkArte/AdminController/ManageSearch.php
  sources/ElkArte/Controller/Search.php
  sources/ElkArte/Database/AbstractSearch.php
  sources/ElkArte/Database/Mysqli/Search.php
  sources/ElkArte/Database/Postgresql/Search.php
  sources/ElkArte/Database/SearchInterface.php
  sources/ElkArte/MessagesDelete.php
  sources/ElkArte/Search/API/AbstractAPI.php
  sources/ElkArte/Search/API/Custom.php
  sources/ElkArte/Search/API/Fulltext.php
  sources/ElkArte/Search/API/Sphinx.php
  sources/ElkArte/Search/API/Sphinxql.php
  sources/ElkArte/Search/API/Standard.php
  sources/ElkArte/Search/Search.php
  sources/ElkArte/Search/SearchApiWrapper.php
  sources/ElkArte/Search/SearchArray.php
  sources/Security.php
  sources/Subs.php
  sources/subs/ManageSearch.subs.php
  sources/subs/Topic.subs.php
  themes/default/ManageSearch.template.php
  themes/default/languages/english/Errors.english.php
  themes/default/languages/english/Help.english.php
  themes/default/languages/english/Search.english.php
Labels: enhancement

#3460 Removed initial default argument on insert
  sources/database/Db-mysql.class.php
  sources/database/Db-postgresql.class.php
  sources/database/Db.php
Labels: db

#3462 Update SCE Commands
  themes/default/scripts/jquery.sceditor.elkarte.js
Labels: enhancement

#3461 Page index problems
  sources/ElkArte/AdminController/BadBehavior.php
  sources/ElkArte/AdminController/ManageErrors.php
  sources/ElkArte/ConstructPageIndex.php
  sources/ElkArte/Controller/Display.php
  sources/ElkArte/Controller/Draft.php
  sources/ElkArte/Controller/Groups.php
  sources/ElkArte/Controller/Memberlist.php
  sources/ElkArte/Controller/MergeTopics.php
  sources/ElkArte/Controller/MessageIndex.php
  sources/ElkArte/Controller/ModerationCenter.php
  sources/ElkArte/Controller/PersonalMessage.php
  sources/ElkArte/Controller/PostModeration.php
  sources/ElkArte/Controller/ProfileInfo.php
  sources/ElkArte/Controller/Recent.php
  sources/ElkArte/Controller/Search.php
  sources/ElkArte/Controller/SplitTopics.php
  sources/ElkArte/Controller/Unread.php
  sources/ElkArte/Controller/Who.php
  sources/ElkArte/TopicUtil.php
  sources/Subs.php
Labels: bug, enhancement

#3465 Header updates
  addons/index.php
  attachments/index.php
  avatars/index.php
  bootstrap.php
  cache/index.php
  packages/index.php
  smileys/index.php
  sources/DumpDatabase.php
  sources/ElkArte/AdminController/ManageServer.php
  sources/ElkArte/Controller/Announce.php
  sources/ElkArte/Controller/Attachment.php
  sources/ElkArte/Controller/Auth.php
  sources/ElkArte/Controller/Calendar.php
  sources/ElkArte/Controller/Jslocale.php
  sources/ElkArte/Controller/News.php
  sources/ElkArte/Controller/OpenID.php
  sources/ElkArte/Controller/PersonalMessage.php
  sources/ElkArte/Controller/Post.php
  sources/ElkArte/Controller/ProfileInfo.php
  sources/ElkArte/Controller/Register.php
  sources/ElkArte/Errors/Errors.php
  sources/ElkArte/Http/Headers.php
  sources/ElkArte/MemberLoader.php
  sources/ElkArte/Request.php
  sources/ElkArte/Server.php
  sources/ElkArte/Themes/Templates.php
  sources/ElkArte/UserSettingsLoader.php
  sources/Load.php
  sources/Security.php
  sources/Session.php
  sources/Subs.php
  sources/index.php
  sources/subs/Attachments.subs.php
  sources/subs/Graphics.subs.php
  sources/subs/Mail.subs.php
  sources/subs/ManageSearch.subs.php
  sources/subs/Sound.subs.php
  subscriptions.php
  themes/default/Theme.php
  themes/default/images/mime_images/index.php
  themes/index.php
Labels: enhancement

#3469 An a few more fixes for 1.1.7
  install/CommonCode.php
  install/Db-check-MySQL.php
  install/Install_Controller.php
  install/TemplateInstall.php
  install/install.php
  install/installcore.php
  sources/database/Db-mysql.class.php
  sources/database/Db-postgresql.class.php
  sources/database/Db.php
  sources/database/DbTable-mysql.php
  sources/subs/ManageSearch.subs.php
  sources/subs/MentionType/MentionTypeInterface.php
  sources/subs/MessageTopicIcons.class.php
  sources/subs/Priority.class.php
  sources/subs/RepairBoards.subs.php
  sources/subs/SessionHandler/SessionHandler.php
  sources/subs/SessionHandler/SessionHandlerInterface.php
  themes/default/languages/english/Install.english.php
Labels: bug, db, enhancement

#3468 Changes to support fulltext on subject
  sources/ElkArte/AdminController/ManageSearch.php
  sources/ElkArte/Search/API/Fulltext.php
  sources/subs/ManageSearch.subs.php
Labels: enhancement

#3470 Partial fix #3463 wrong quote attribute on modify
  sources/controllers/Post.controller.php
  sources/subs/MentionType/QuotedmemMention.php
  sources/subs/Mentioning.php
Labels: bug
