Repository elkarte/Elkarte, pull requests merged in 2022-03, with the labels that each got.

#3607 A few fixes
  install/install_2-0.php
  sources/ElkArte/AdminController/ManageAttachments.php
  sources/ElkArte/AdminController/ManageSecurity.php
  sources/ElkArte/Languages/Loader.php
  sources/subs/Attachments.subs.php
  themes/default/GenericMessages.template.php
  themes/default/Post.template.php
  themes/default/css/_besocial/index_besocial.css
  themes/default/css/_light/index_light.css
  themes/default/css/index.css
  themes/default/scripts/dropAttachments.js
Labels: bug

#3605 Packman
  .gitignore
  sources/ElkArte/AbstractModel.php
  sources/ElkArte/AdminController/Admin.php
  sources/ElkArte/AdminController/ManageSmileys.php
  sources/ElkArte/Controller/Auth.php
  sources/ElkArte/FileFunctions.php
  sources/ElkArte/Http/FtpConnection.php
  sources/ElkArte/Languages/Packages/English.php
  sources/ElkArte/Packages/PackageActions.php
  sources/ElkArte/Packages/PackageChmod.php
  sources/ElkArte/Packages/PackageParser.php
  sources/ElkArte/Packages/PackageServers.php
  sources/ElkArte/Packages/Packages.php
  sources/ElkArte/Packages/PackagesFilterIterator.php
  sources/ElkArte/UnTgz.php
  sources/ElkArte/UnZip.php
  sources/subs/Package.subs.php
  tests/sources/admin/PackagesTest.php
  themes/default/PackageServers.template.php
  themes/default/Packages.template.php
  themes/default/css/_light/admin_light.css
  themes/default/css/admin.css
  themes/default/scripts/admin.js
Labels: bug, enhancement

#3610 Mail
  sources/ElkArte/Controller/ScheduledTasks.php
  sources/ElkArte/Mail/BaseMail.php
  sources/ElkArte/Mail/BuildMail.php
  sources/ElkArte/Mail/Mail.php
  sources/ElkArte/Mail/QueueMail.php
  sources/subs/Mail.subs.php
Labels: enhancement

#3611 Theme pick
  sources/ElkArte/AdminController/ManageThemes.php
  sources/ElkArte/Controller/Auth.php
  sources/ElkArte/Controller/Profile.php
  sources/ElkArte/Controller/ProfileOptions.php
  sources/subs/Themes.subs.php
  themes/default/ManageThemes.template.php
  themes/default/ProfileOptions.template.php
Labels: enhancement

#3612 Break display controller into a series of methods
  sources/ElkArte/Controller/Display.php
  sources/ElkArte/Modules/Poll/Display.php
  themes/default/Display.template.php
Labels: enhancement

#3618 Various
  install/install_1-1.php
  sources/admin/PackageServers.controller.php
  sources/subs/Mail.subs.php
  themes/default/Post.template.php
  themes/default/css/_besocial/index_besocial.css
  themes/default/css/_light/index_light.css
  themes/default/css/icons_svg.css
  themes/default/css/index.css
  themes/default/css/rtl.css
  themes/default/index.template.php
  themes/default/scripts/script_elk.js
Labels: bug

#3620 A bunch of fixes and partial addressing #3614
  sources/ElkArte/AdminController/ManageAttachments.php
  sources/ElkArte/AttachmentsDisplay.php
  sources/ElkArte/Controller/Display.php
  sources/ElkArte/Controller/Emailuser.php
  sources/ElkArte/Controller/PersonalMessage.php
  sources/ElkArte/Controller/Post.php
  sources/ElkArte/Controller/ProfileInfo.php
  sources/ElkArte/Controller/ProfileOptions.php
  sources/ElkArte/Controller/Recent.php
  sources/ElkArte/Controller/Register.php
  sources/ElkArte/Controller/Search.php
  sources/ElkArte/IlaIntegrate.php
  sources/ElkArte/MessagesCallback/DisplayRenderer.php
  sources/ElkArte/MessagesCallback/SearchRenderer.php
  sources/ElkArte/Modules/Attachments/Display.php
  sources/ElkArte/Modules/Random/Display.php
  sources/ElkArte/Packages/PackageServers.php
  sources/ElkArte/Packages/Packages.php
  sources/ElkArte/Search/API/Fulltext.php
  sources/ElkArte/Search/Search.php
  sources/subs/Attachments.subs.php
  themes/default/Display.template.php
  themes/default/Emailuser.template.php
  themes/default/GenericMessages.template.php
  themes/default/PackageServers.template.php
  themes/default/Packages.template.php
  themes/default/Post.template.php
  themes/default/ProfileInfo.template.php
  themes/default/ProfileOptions.template.php
  themes/default/Register.template.php
  themes/default/Theme.php
  themes/default/scripts/like_posts.js
Labels: bug, enhancement

#3617 Site Fixes
  sources/ElkArte/AdminController/ManageTopics.php
  sources/ElkArte/Controller/Display.php
  sources/ElkArte/Controller/Stats.php
  sources/ElkArte/Languages/Index/English.php
  sources/ElkArte/Mail/QueueMail.php
  sources/ElkArte/Modules/Poll/Display.php
  sources/ElkArte/Modules/Poll/Post.php
  sources/subs/Recent.subs.php
  sources/subs/Stats.subs.php
  themes/default/Display.template.php
  themes/default/GenericMessages.template.php
  themes/default/Post.template.php
  themes/default/css/index.css
  themes/default/css/rtl.css
  themes/default/scripts/script.js
  themes/default/scripts/script_elk.js
  themes/default/scripts/stats.js
  themes/default/scripts/topic.js
Labels: bug
