Repository elkarte/Elkarte, pull requests merged in 2022-01, with the labels that each got.

#3533 PHP 8.1 strftime and gmstrftime changes
  SSI.php
  install/Install_Controller.php
  install/patch_1-1-4/1.1.4/Agreement.class.php
  packages/installed.list
  sources/DumpDatabase.php
  sources/Load.php
  sources/Logging.php
  sources/Subs.php
  sources/admin/ManageCalendarModule.controller.php
  sources/admin/ManagePaid.controller.php
  sources/controllers/News.controller.php
  sources/controllers/Register.controller.php
  sources/controllers/Stats.controller.php
  sources/modules/Calendar/CalendarPostModule.class.php
  sources/subs/Agreement.class.php
  sources/subs/Calendar.subs.php
  sources/subs/CalendarEvent.class.php
  sources/subs/Memberlist.subs.php
  sources/subs/Members.subs.php
  sources/subs/MembersOnline.subs.php
  sources/subs/Package.subs.php
  sources/subs/Profile.subs.php
  sources/subs/SearchEngines.subs.php
  sources/subs/Util.class.php
  themes/default/Xml.template.php
  themes/default/languages/english/Help.english.php
Labels: bug, enhancement

#3532 Site triage and 1.1.8 pull in
  bootstrap.php
  sources/ElkArte/AdminController/ManageErrors.php
  sources/ElkArte/AdminController/ManageFeatures.php
  sources/ElkArte/Controller/Attachment.php
  sources/ElkArte/Controller/Display.php
  sources/ElkArte/Controller/Mentions.php
  sources/ElkArte/Errors/Errors.php
  sources/ElkArte/Html2Md.php
  sources/ElkArte/Mentions/Mentioning.php
  sources/ElkArte/ScheduledTasks/Tasks/UserAccessMentions.php
  sources/ElkArte/Themes/ThemeLoader.php
  sources/ElkArte/Util.php
  sources/subs/Mail.subs.php
  sources/subs/ManageAttachments.subs.php
  sources/subs/ManageFeatures.subs.php
  tests/sources/subs/HTML2Md.class.Basic.php
  tests/sources/subs/Http/Stream_Fetch_Webdata.class.Test.php
  themes/default/Login.template.php
  themes/default/ManageBoards.template.php
  themes/default/Theme.php
  themes/default/css/_besocial/jquery.sceditor.elk_wiz_besocial.css
  themes/default/css/_light/jquery.sceditor.elk_wiz_light.css
  themes/default/css/index.css
  themes/default/languages/english/Maintenance.english.php
  themes/default/languages/english/ManageSettings.english.php
  themes/default/scripts/jquery-3.5.1.min.js
  themes/default/scripts/jquery-3.6.0.min.js
Labels: bug, theme, Security

#3541 Converters
  sources/ElkArte/AdminController/ManageMaillist.php
  sources/ElkArte/Converters/AbstractDomParser.php
  sources/ElkArte/Converters/Html2BBC.php
  sources/ElkArte/Converters/Html2Md.php
  sources/ElkArte/Html2BBC.php
  sources/ElkArte/Html2Md.php
  sources/subs/Emailpost.subs.php
  sources/subs/Members.subs.php
  tests/sources/subs/HTML2BBC.class.Basic.php
  tests/sources/subs/HTML2Md.class.Basic.php
  tests/sources/subs/MD2HTML.class.Basic.php
Labels: bug, enhancement

#3557 Additional Attachment Updates
  sources/ElkArte/AdminController/ManageAttachments.php
  sources/ElkArte/AttachmentsDirectory.php
  sources/ElkArte/Controller/Attachment.php
  sources/ElkArte/Errors/AttachmentErrorContext.php
  sources/ElkArte/FileFunctions.php
  sources/ElkArte/Graphics/Image.php
  sources/ElkArte/Graphics/ImageUploadResize.php
  sources/ElkArte/Graphics/Manipulators/AbstractManipulator.php
  sources/ElkArte/Graphics/Manipulators/Gd2.php
  sources/ElkArte/Graphics/Manipulators/Imagick.php
  sources/ElkArte/Graphics/TextImage.php
  sources/ElkArte/Modules/Attachments/Post.php
  sources/ElkArte/ScheduledTasks/Tasks/RemoveTempAttachments.php
  sources/ElkArte/TemporaryAttachment.php
  sources/ElkArte/TemporaryAttachmentsList.php
  sources/subs/Attachments.subs.php
  sources/subs/ManageAttachments.subs.php
  sources/subs/Profile.subs.php
  tests/sources/subs/Http/Curl_Fetch_Webdata.class.Test.php
  tests/sources/subs/Http/Fsock_Fetch_Webdata.class.Test.php
  themes/default/Post.template.php
  themes/default/css/_light/index_light.css
  themes/default/css/admin.css
  themes/default/css/icons_svg.css
  themes/default/languages/english/Admin.english.php
  themes/default/languages/english/Errors.english.php
  themes/default/languages/english/Help.english.php
  themes/default/languages/english/Post.english.php
  themes/default/languages/english/index.english.php
  themes/default/scripts/dropAttachments.js
Labels: bug, enhancement

#3562 Next batch of fixes
  index.php
  sources/ElkArte/AdminController/ManageBans.php
  sources/ElkArte/AdminController/ManageEmojiModule.php
  sources/ElkArte/AdminController/ManageErrors.php
  sources/ElkArte/AdminController/Modlog.php
  sources/ElkArte/BBC/BBCParser.php
  sources/ElkArte/ConstructPageIndex.php
  sources/ElkArte/Controller/Likes.php
  sources/ElkArte/Controller/Memberlist.php
  sources/ElkArte/Controller/Notify.php
  sources/ElkArte/Controller/ProfileOptions.php
  sources/ElkArte/Emoji.php
  sources/ElkArte/Errors/Log.php
  sources/ElkArte/Event.php
  sources/ElkArte/EventManager.php
  sources/ElkArte/HttpReq.php
  sources/ElkArte/Mentions/MentionType/AbstractEventBoardAccess.php
  sources/ElkArte/Mentions/MentionType/AbstractEventMessage.php
  sources/ElkArte/Mentions/MentionType/Event/Buddy.php
  sources/ElkArte/Mentions/MentionType/Event/Likemsg.php
  sources/ElkArte/Mentions/MentionType/Event/Mailfail.php
  sources/ElkArte/Mentions/MentionType/Event/Mentionmem.php
  sources/ElkArte/Mentions/MentionType/Event/Quotedmem.php
  sources/ElkArte/Mentions/MentionType/Event/Rlikemsg.php
  sources/ElkArte/Mentions/MentionType/Notification/Buddy.php
  sources/ElkArte/Mentions/MentionType/Notification/Likemsg.php
  sources/ElkArte/Mentions/MentionType/Notification/Mailfail.php
  sources/ElkArte/Mentions/MentionType/Notification/Mentionmem.php
  sources/ElkArte/Mentions/MentionType/Notification/Quotedmem.php
  sources/ElkArte/Mentions/MentionType/Notification/Rlikemsg.php
  sources/ElkArte/Mentions/Mentioning.php
  sources/ElkArte/Menu/Menu.php
  sources/ElkArte/MessagesCallback/DisplayRenderer.php
  sources/ElkArte/MessagesCallback/Renderer.php
  sources/ElkArte/Modules/AbstractModule.php
  sources/ElkArte/Modules/Mentions/AbstractMentions.php
  sources/ElkArte/SettingsForm/SettingsForm.php
  sources/ElkArte/SettingsForm/SettingsFormAdapter/Db.php
  sources/ElkArte/Themes/ThemeLoader.php
  sources/ElkArte/UrlGenerator/Standard/Profile.php
  sources/ElkArte/UrlGenerator/Standard/Standard.php
  sources/ElkArte/UserNotification.php
  sources/ElkArte/UserNotificationIntegrate.php
  sources/ElkArte/ValuesContainer.php
  sources/Load.php
  sources/Subs.php
  sources/subs/Modlog.subs.php
  sources/subs/Notification.subs.php
  themes/default/Admin.template.php
  themes/default/GenericMenu.template.php
  themes/default/css/index.css
  themes/default/scripts/drafts.js
  themes/default/scripts/emoji.plugin.js
  themes/default/scripts/jquery.sceditor.elkarte.js
  themes/default/scripts/like_posts.js
  themes/default/scripts/script_elk.js
Labels: bug

#3563 Only docblock the exceptions from where they are actually thrown
  sources/subs/Admin.subs.php
  sources/subs/Attachments.subs.php
  sources/subs/Auth.subs.php
  sources/subs/Bans.subs.php
  sources/subs/Cache.subs.php
  sources/subs/Calendar.subs.php
  sources/subs/Categories.subs.php
  sources/subs/Drafts.subs.php
  sources/subs/Editor.subs.php
  sources/subs/Emailpost.subs.php
  sources/subs/FollowUps.subs.php
  sources/subs/Karma.subs.php
  sources/subs/Language.subs.php
  sources/subs/Likes.subs.php
  sources/subs/Logging.subs.php
  sources/subs/Mail.subs.php
  sources/subs/Maillist.subs.php
  sources/subs/Maintenance.subs.php
  sources/subs/ManageFeatures.subs.php
  sources/subs/ManagePermissions.subs.php
  sources/subs/Membergroups.subs.php
  sources/subs/Memberlist.subs.php
  sources/subs/Members.subs.php
  sources/subs/MembersOnline.subs.php
  sources/subs/Mentions.subs.php
  sources/subs/Menu.subs.php
  sources/subs/MessageIcons.subs.php
  sources/subs/MessageIndex.subs.php
  sources/subs/Messages.subs.php
  sources/subs/Moderation.subs.php
  sources/subs/Modlog.subs.php
  sources/subs/News.subs.php
  sources/subs/Notification.subs.php
  sources/subs/Package.subs.php
  sources/subs/PackageServers.subs.php
  sources/subs/PaidSubscriptions.subs.php
  sources/subs/PersonalMessage.subs.php
  sources/subs/Poll.subs.php
  sources/subs/Post.subs.php
  sources/subs/Profile.subs.php
  sources/subs/ProfileHistory.subs.php
  sources/subs/ProfileOptions.subs.php
  sources/subs/Recent.subs.php
  sources/subs/RepairBoards.subs.php
  sources/subs/Reports.subs.php
  sources/subs/ScheduledTasks.subs.php
  sources/subs/SearchEngines.subs.php
  sources/subs/Smileys.subs.php
  sources/subs/Stats.subs.php
  sources/subs/Themes.subs.php
  sources/subs/Topic.subs.php
  sources/subs/Who.subs.php
Labels: enhancement

#3567 Switches Likes to Reacts Elkarte2
  sources/ElkArte/Controller/Display.php
  sources/ElkArte/Controller/Recent.php
  themes/default/Display.template.php
  themes/default/css/index.css
  themes/default/scripts/like_posts.js
Labels: enhancement

#3571 Update html2md so it does not break links
  sources/subs/Html2Md.class.php
  themes/default/Display.template.php
Labels: bug

#3573 Couple of language loader typo's
  sources/ElkArte/AdminController/ManageRegistration.php
  sources/ElkArte/AdminController/ManageThemes.php
  sources/ElkArte/Controller/Notify.php
  sources/ElkArte/Errors/Errors.php
  sources/ElkArte/Languages/Loader.php
  sources/ElkArte/Modules/Drafts/Profile.php
  sources/ElkArte/ScheduledTasks/Tasks/ApprovalNotification.php
  sources/subs/Mail.subs.php
  sources/subs/Themes.subs.php
Labels: enhancement

#3574 Next Batch of Fixes
  sources/ElkArte/AdminController/Admin.php
  sources/ElkArte/AdminController/ManageAttachments.php
  sources/ElkArte/Controller/Likes.php
  sources/ElkArte/Controller/News.php
  sources/ElkArte/Controller/Notify.php
  sources/ElkArte/Controller/ProfileInfo.php
  sources/ElkArte/Converters/Html2Md.php
  sources/ElkArte/Languages/Index/English.php
  sources/ElkArte/Notifications.php
  sources/ElkArte/TopicUtil.php
  sources/ElkArte/UserSettings.php
  sources/ElkArte/UserSettingsLoader.php
  sources/subs/Menu.subs.php
  sources/subs/News.subs.php
  themes/default/Admin.template.php
  themes/default/Announce.template.php
  themes/default/Display.template.php
  themes/default/GenericBoards.template.php
  themes/default/ManageAttachments.template.php
  themes/default/ManageNews.template.php
  themes/default/ManageSearch.template.php
  themes/default/Packages.template.php
  themes/default/PersonalMessage.template.php
  themes/default/Post.template.php
  themes/default/ProfileInfo.template.php
  themes/default/Theme.php
  themes/default/Xml.template.php
  themes/default/css/_besocial/icons_svg_besocial.css
  themes/default/css/_besocial/index_besocial.css
  themes/default/css/_light/index_light.css
  themes/default/css/icons_svg.css
  themes/default/css/index.css
  themes/default/css/rtl.css
  themes/default/index.template.php
  themes/default/scripts/dropAttachments.js
  themes/default/scripts/elk_jquery_embed.js
  themes/default/scripts/like_posts.js
  themes/default/scripts/profile.js
  themes/default/scripts/script.js
  themes/default/scripts/topic.js
Labels: bug, enhancement

#3575 Mark as read controller
  sources/ElkArte/Controller/Markasread.php
  sources/ElkArte/SiteDispatcher.php
  themes/default/scripts/script_elk.js
Labels: bug, enhancement

#3576 Avatars
  avatars_user/index.php
  sources/ElkArte/AdminController/ManageAttachments.php
  sources/ElkArte/AdminController/ManageAvatars.php
  sources/ElkArte/AdminController/Packages.php
  sources/ElkArte/Controller/Attachment.php
  sources/ElkArte/Controller/Avatars.php
  sources/ElkArte/FileFunctions.php
  sources/ElkArte/Graphics/Image.php
  sources/ElkArte/Graphics/ImageUploadResize.php
  sources/ElkArte/Graphics/Manipulators/Imagick.php
  sources/ElkArte/Graphics/TextImage.php
  sources/ElkArte/Languages/Admin/English.php
  sources/ElkArte/Languages/Errors/English.php
  sources/ElkArte/Languages/Help/English.php
  sources/ElkArte/Languages/Post/English.php
  sources/ElkArte/Languages/Profile/English.php
  sources/ElkArte/Modules/Attachments/Post.php
  sources/ElkArte/TemporaryAttachment.php
  sources/Load.php
  sources/Security.php
  sources/subs/Attachments.subs.php
  sources/subs/ManageAttachments.subs.php
  sources/subs/Package.subs.php
  sources/subs/Profile.subs.php
  themes/default/Post.template.php
  themes/default/ProfileOptions.template.php
  themes/default/css/_besocial/index_besocial.css
  themes/default/css/_light/index_light.css
  themes/default/css/index.css
  themes/default/scripts/dropAttachments.js
  themes/default/scripts/profile.js
Labels: bug, enhancement
